---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Create nftables conf directory when needed
  ansible.builtin.file:
    path: /etc/nftables.conf.d
    state: directory
    mode: 0755

- name: Install basic nftables portlists
  ansible.builtin.template:
    src: etc/nftables.conf.d/nftbase.nft.j2
    dest: /etc/nftables.conf.d/nftbase.nft
    backup: no
  notify: Restart nftables

- name: Install nftables config file
  ansible.builtin.template:
    src: etc/nftables.conf.j2
    dest: /etc/nftables.conf
    backup: no
  notify: Restart nftables

- name: Create systemd override directory for nftables
  ansible.builtin.file:
    path: /etc/systemd/system/nftables.service.d
    state: directory
    mode: '0755'

- name: Propagate nft reloads to fail2ban
  ansible.builtin.copy:
    src: etc/systemd/system/nftables.service.d/override.conf
    dest: /etc/systemd/system/nftables.service.d/override.conf
  notify: Restart nftables
