---

- name: Restart nftables for openvpn
  ansible.builtin.systemd:
    name: nftables.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart openvpn
  ansible.builtin.systemd:
    name: openvpn-server@{{ openvpn_server_name }}.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
