
- name: Debian Router Setup (DEVEL)
  hosts: mimas99
  become: true
  roles:
  - upv6if
  - bridges
  - vlanifs
  - nft
  - fail2ban
  - routing
  - dnsmasq
  - openvpn
  ### afraid / unifi not on DEVEL
  #- afraid
  #- unifi

- name: Debian Router Setup (PROD)
  hosts: mimas
  become: true
  roles:
  - upv6if
  - bridges
  - vlanifs
  - nft
  - fail2ban
  - routing
  - dnsmasq
  - openvpn
  - afraid
  - unifi
