---

- name: Restart nftables for avahi
  ansible.builtin.systemd:
    name: nftables.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
