---

- name: Restart nftables for igmpproxy
  ansible.builtin.systemd:
    name: nftables.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart igmpproxy
  ansible.builtin.systemd:
    name: igmpproxy.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
