---

  # the install part of this playbook is an ansible implementation of the instructions here:
  # https://help.ui.com/hc/en-us/articles/220066768-Updating-and-Installing-Self-Hosted-UniFi-Network-Servers-Linux

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Open ports needed for unifi
  ansible.builtin.template:
    src: etc/nftables.conf.d/unifi.nft.j2
    dest: /etc/nftables.conf.d/unifi.nft
    backup: no
  notify: "Restart nftables for unifi"

- name: Install ca-certificates and apt-transport-https
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present

- name: Configure mongodb repo
  ansible.builtin.deb822_repository:
    name: mongodb-org-8.0
    types: deb
    uris: https://repo.mongodb.org/apt/debian
    suites: bookworm/mongodb-org/8.0
    components: main
    signed_by: https://pgp.mongodb.com/server-8.0.asc
  register: mongorepo

- name: Create subdirs needed for next step
  ansible.builtin.file:
    path: /etc/crypto-policies/back-ends
    state: directory
    mode: '755'

# See https://community.ui.com/questions/Unifi-debian-repo-error/9dfaf8b5-84dd-4123-9d7b-229f7b6091f3
- name: Accept SHA1 a little longer for Repo signing (unifi)
  ansible.builtin.template:
    src: etc/crypto-policies/back-ends/apt-sequoia.config.j2
    dest: /etc/crypto-policies/back-ends/apt-sequoia.config
    backup: no
  register: aptsequoia

- name: Configure unifi repo
  ansible.builtin.deb822_repository:
    name: unifi-stable
    types: deb
    uris: https://www.ui.com/downloads/unifi/debian
    suites: stable
    components: ubiquiti
    signed_by: https://dl.ui.com/unifi/unifi-repo.gpg
  register: unifirepo

- name: update apt cache if repo changed
  ansible.builtin.apt:
    update_cache: yes
  when: mongorepo.changed or aptsequoia.changed or unifirepo.changed

- name: install mongodb-org, unifi
  ansible.builtin.apt:
    name:
      - mongodb-org
      - unifi
    state: present
  notify: "Restart unifi"
  ignore_errors: "{{ ansible_check_mode }}"
