---

- name: Restart nftables for dnsmasq
  ansible.builtin.systemd:
    name: nftables.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
