---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Install bridge config file
  ansible.builtin.template:
    src: templates/etc/network/interfaces.d/bridges.j2
    dest: /etc/network/interfaces.d/bridges
    backup: no

#- block:
#  - name: get bridge status of {{ item.name }}
#    ansible.builtin.command:
#      cmd: ip a show {{ item.name }}
#    register: ifacestatus
#
#  - name: show bridge status
#    ansible.builtin.debug:
#      msg: "{{ ifacestatus }}"
#
#  loop: "{{ bridges }}"

- name: Start bridge if not running yet
  ansible.builtin.debug:
    msg: "Bridge {{ item.name }}"
  loop: "{{ bridges }}"
