---

# to be included in a loop

- name: show current loop name
  ansible.builtin.debug:
    msg: "Running reboot/restart checks for {{ item.name }}" 

- name: reboot if bridge interface not in ansible_facts
  ansible.builtin.reboot:
    msg: "{{ item.name }} is not defined, reboot"
  when: ansible_facts[item.name] is not defined

- name: get current ip from ansible_facts
  ansible.builtin.set_fact:
    currentip: "{{ ansible_facts[item.name].ipv4.address | default('NOIP')}}"

- name: restart bridge interface if config changed or wrong IP-address
  ansible.builtin.shell:
    cmd: "ifdown {{ item.name }}; ifup {{ item.name }}"
  when: ( currentip != item.address ) or configbridge.changed


