---

# to be included in a loop

- name: show current loop name
  ansible.builtin.debug:
    msg: "Running restart checks for bridge {{ item.name }}"

- name: get current ip from ansible_facts
  ansible.builtin.set_fact:
    currentip: "{{ ansible_facts[item.name].ipv4.address | default('NOIP') }}"

- name: restart bridge interface if config changed or wrong IP-address
  ansible.builtin.shell:
    cmd: "ifdown {{ item.name }}; ifup {{ item.name }}"
  when: ( currentip != item.address ) or configbridge.changed


