---

# to be included in a loop

- name: show current loop name
  ansible.builtin.debug:
    msg: "Running restart checks for bridge {{ item.name }}"

- name: get current ipv4 from ansible_facts
  ansible.builtin.set_fact:
    currentv4ip: "{{ ansible_facts[item.name].ipv4.address | default('NOIP') }}"

- name: get current ipv6 from ansible_facts
  ansible.builtin.set_fact:
    currentv6ip: '{{ansible_facts[item.name].ipv6 | selectattr ( "scope", "equalto", "global" ) | map ( attribute="address" ) | first | default("NoV6") }}/{{ ansible_facts[item.name].ipv6 | selectattr ( "scope", "equalto", "global" ) | map ( attribute="prefix" ) | first | default("NoLen") }}'

- name: restart bridge interface if config changed or wrong IP-address
  ansible.builtin.shell:
    cmd: "ifdown {{ item.name }}; ifup {{ item.name }}"
  when: ( currentv4ip != item.v4info.address ) or (currentv6ip != item.v6info.address) or configbridge.changed


