---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Config fail2ban to use nftables
  ansible.builtin.copy:
    src: etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
  register: configfail2ban

- name: Add filter rule for openvpn
  ansible.builtin.copy:
    src: etc/fail2ban/filter.d/openvpn.local
    dest: /etc/fail2ban/filter.d/openvpn.local
  register: configfail2banopenvpnfilter

- name: Configure jail for openvpn
  ansible.builtin.template:
    src: etc/fail2ban/jail.d/openvpn.local.j2
    dest: /etc/fail2ban/jail.d/openvpn.local
  register : configfail2banopenvpnjail

- name: Configure jail for recidive
  ansible.builtin.template:
    src: etc/fail2ban/jail.d/recidive.local.j2
    dest: /etc/fail2ban/jail.d/recidive.local
  register : configfail2banrecidivejail

- name: Ensure fail2ban is active and started
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: yes
  when: configfail2ban.changed or configfail2banopenvpnfilter.changed or configfail2banopenvpnjail.changed or configfail2banrecidivejail.changed
