---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Add routing option to sysctl
  ansible.builtin.copy:
    content: |
      # Enable IPv4 routing on all interfaces
      net.ipv4.ip_forward=1
    dest: /etc/sysctl.d/local.conf
  notify: Restart sysctl
