---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Open ports needed to answer dns requests
  ansible.builtin.template:
    src: templates/etc/nftables.conf.d/dnsmasq.nft.j2
    dest: /etc/nftables.conf.d/dnsmasq.nft
    backup: no
  register: nftconfig

- name: Enable / Restart nftables when config files changed
  ansible.builtin.systemd:
    name: "nftables.service"
    state: restarted
    enabled: yes
  when: nftconfig.changed

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Install dnsmasq config file
  ansible.builtin.template:
    src: templates/etc/dnsmasq.d/localconf.j2
    dest: /etc/dnsmasq.d/localconf
    backup: no
  register: configdnsmasq

- name: restart dnsmasq
  ansible.builtin.systemd:
    name: "dnsmasq.service"
    state: restarted
    enabled: yes
  when: configdnsmasq.changed

