---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Open ports needed to answer dns requests
  ansible.builtin.template:
    src: etc/nftables.conf.d/dnsmasq.nft.j2
    dest: /etc/nftables.conf.d/dnsmasq.nft
    backup: no
  notify: Restart nftables for dnsmasq

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Install dnsmasq config file
  ansible.builtin.template:
    src: etc/dnsmasq.d/localconf.j2
    dest: /etc/dnsmasq.d/localconf
    backup: no
  notify: Restart dnsmasq

- name: ensure some static hosts file is present
  ansible.builtin.copy:
    src: "{{ dnsmasq_dhcp_staticips_source }}"
    dest: /etc/dnsmasq.d/staticips
    force: no
  notify: Restart dnsmasq
