# upv6if role

upv6if_iface: enp1s0
##  With prefix delegation (PROD)
#
#upv6if_expected_delegation: "2001:db8:1234:6f0::/60"
#
#upv6if_mode: dhcp
#upv6if_configlines:
#  - "request_prefix 1"
#  - "accept_ra 2"

##  With static IPv6 (TEST)

upv6if_mode: static
upv6if_configlines:
  - "address 2001:db8:1234:6f0::2/64"
  - "accept_ra 2"

# bridges role
bridges:
  - name: "br0"
    members:
      - enp2s0
      - enp3s0
    v4info:
      address: 172.30.0.1
      netmask: 255.255.254.0
      broadcast: 172.30.1.255
      routes:
        - target: 10.10.10.0/24
          gw: 172.30.0.134
    v6info:
      address: 2001:db8:1234:6f2::1/64
      # v6 routes, not used in lab
      # routes:

# vlanifs role

vlanifs:
  - number: "700"
    baseif: "br0"
    v4info:
      address: 172.27.0.1
      netmask: 255.255.255.0
      broadcast: 172.27.0.255
    # not used in lab
    #v6info:
    #  address: 

# nft role

nft_upstream_interface: enp1s0
nft_mgmt_interface: br0
nft_downstream_interfaces:
  - br0
  - br0.700

# fail2ban role: nothing host specific (until now)
# routing role: nothing host specific (until now)

# avahi role
#
avahi_interfaces:
  - br0
  - br0.700

# dnsmasq role

dnsmasq_except_interface: enp1s0

dnsmasq_other_servers:
  - name: UCS Domains
    domains:
      - t7.example.com
      - 0.26.172.in-addr.arpa
    serverips:
      - 172.26.0.10
      - 172.26.0.12

dnsmasq_dhcp_domain: example.com

dnsmasq_dhcp_search_domain_names:
  - example.ch
  - example.net

dnsmasq_dhcp_staticips_source: ~/staticips

dnsmasq_dhcp_ranges:
  - name: LANv4
    rangeline: "172.30.0.100,172.30.0.199,24h"
  - name: LANv6
    rangeline: "2001:db8:1234:6f2::1:1,2001:db8:1234:6f2::ffff:1,ra-names,64,24h"
  # not used in lab
  #- name: WLAN
  #  range: "172.27.0.10,172.27.0.199"
  #  leasetime: "12h"

# afraid role, not applicable on test machines without 
# direct internet connectivity

# afraid_external_vpn_interface: enp1s0
# afraid_domain_name: example.domain.com

# openvpn role

openvpn_server_interfaces:
  - enp1s0
openvpn_server_ip: 10.8.0.0
openvpn_server_mask: 255.255.255.0
openvpn_server_ipv6: 2001:db8:1234:6f3::1/64
openvpn_server_name: mimasvpn
openvpn_dhfile_source: ~/vpnsecrets/dh.pem
openvpn_cafile_source: ~/vpnsecrets/ca.crt
openvpn_certfile_source: ~/vpnsecrets/issued/server.crt
openvpn_keyfile_source: ~/vpnsecrets/private/server.key

openvpn_pushroutes:
  - address: 172.30.0.0
    mask: 255.255.254.0
  - address: 172.27.0.1
    mask: 255.255.255.0

openvpn_pushroutes_ipv6:
  - address: 2001:db8:1234:6f0::/60

openvpn_client_options:
  - name: zeta
    options:
      - 'push "comp-lzo yes"'
      - 'comp-lzo yes'
  - name: alpha
    dnsoption: yes
  - name: lambda
    dnsoption: yes

openvpn_client_push_dns:
  dnsserverips:
    - 10.8.0.1
  dnsdomains:
    - example.net
    - example.org

openvpn_dns_domain: vpn.example.net

openvpn_nft_targets_smb:
  v4info:
    - 172.30.0.126
  #v6info:
openvpn_nft_targets_imaps:
  v4info:
    - 172.30.0.126
  #v6info:

# can only refer to hosts that had a successful openvpn connect once 
# i.e. are in ipp.txt
openvpn_nft_client_rules:
  - name: localhost_dns
    clients:
      - lambda
      #- alpha
  - name: localhost_ssh
    clients:
      - lambda
      #- alpha
  - name: localhost_unifi
    clients:
      - lambda
      #- zeta
  - name: localnet_ssh
    clients:
      - lambda
  - name: localnet_smb
    clients:
      - lambda
  - name: localnet_music
    clients:
      - lambda
  - name: localnet_imaps
    clients:
      - lambda

openvpn_nft_nbd_source_ipv4: 172.30.0.17
openvpn_nft_service_rules:
  - name: client_nbd
    clients:
      - lambda

# unifi role: nothing host specific (until now)
