
# bridges role
bridges:
  - name: "br0"
    members:
      - enp2s0
      - enp3s0
    address: 172.30.0.1
    netmask: 255.255.254.0
    broadcast: 172.30.1.255

# vlanifs role

vlanifs:
  - number: "700"
    baseif: "br0"
    address: 172.27.0.1
    netmask: 255.255.255.0
    broadcast: 172.27.0.255

# nft role

nft_upstream_interface: enp1s0
nft_mgmt_interface: br0
nft_downstream_interfaces:
  - br0
  - br0.700

# unifi role: nothing host specific (until now)

# dnsmasq role

dnsmasq_except_interface: enp1s0

dnsmasq_dhcp_search_domain_names:
  - iselin.ch
  - iselin.net

dnsmasq_other_servers:
  - name: UCS Domains
    domains:
      - t7.iselin.net
      - 0.25.172.in-addr.arpa
    serverips:
      - 172.25.0.10
      - 172.25.0.12

dnsmasq_dhcp_staticips_source: ~/staticips

dnsmasq_dhcp_ranges:
  - name: LAN
    range: "172.30.0.100,172.30.0.199"
    leasetime: "24h"
  - name: WLAN
    range: "172.27.0.10,172.27.0.199"
    leasetime: "12h"

# openvpn role

openvpn_server_name: mimasvpn
openvpn_dhfile_source: ~/vpnsecrets/dh.pem
openvpn_cafile_source: ~/vpnsecrets/ca.crt
openvpn_certfile_source: ~/vpnsecrets/issued/server.crt
openvpn_keyfile_source: ~/vpnsecrets/private/server.key
