
# bridges role
bridges:
  - name: "br0"
    members:
      - enp2s0
      - enp3s0
    address: 172.30.0.1
    netmask: 255.255.254.0
    broadcast: 172.30.1.255
    routes:
      - target: 10.10.10.0/24
        gw: 172.30.0.134
      - target: 10.10.20.0/24
        gw: 172.30.0.134

# vlanifs role

vlanifs:
  - number: "700"
    baseif: "br0"
    address: 172.27.0.1
    netmask: 255.255.255.0
    broadcast: 172.27.0.255

# nft role

nft_upstream_interface: enp1s0
nft_mgmt_interface: br0
nft_downstream_interfaces:
  - br0
  - br0.700

# unifi role: nothing host specific (until now)

# dnsmasq role

dnsmasq_except_interface: enp1s0

dnsmasq_other_servers:
  - name: UCS Domains
    domains:
      - t7.example.com
      - 0.26.172.in-addr.arpa
    serverips:
      - 172.26.0.10
      - 172.26.0.12

dnsmasq_dhcp_domain: example.com

dnsmasq_dhcp_search_domain_names:
  - example.ch
  - example.net

dnsmasq_dhcp_staticips_source: ~/staticips

dnsmasq_dhcp_ranges:
  - name: LAN
    range: "172.30.0.100,172.30.0.199"
    leasetime: "24h"
  - name: WLAN
    range: "172.27.0.10,172.27.0.199"
    leasetime: "12h"

# afraid role

afraid_external_vpn_interface: enp1s0
afraid_domain_name: example.domain.com

# openvpn role

openvpn_server_interfaces:
  - enp1s0
openvpn_server_ip: 10.8.0.0
openvpn_server_mask: 255.255.255.0
openvpn_server_name: mimasvpn
openvpn_dhfile_source: ~/vpnsecrets/dh.pem
openvpn_cafile_source: ~/vpnsecrets/ca.crt
openvpn_certfile_source: ~/vpnsecrets/issued/server.crt
openvpn_keyfile_source: ~/vpnsecrets/private/server.key

openvpn_pushroutes:
  - address: 172.30.0.0
    mask: 255.255.254.0
  - address: 172.27.0.1
    mask: 255.255.255.0

openvpn_push_dns:
  clientlist:
    - alpha
    - lambda
  dnsserverips:
    - 10.8.0.1
  dnsdomains:
    - example.net
    - example.org

openvpn_nft_targets_smb:
  - 172.30.0.126
openvpn_nft_targets_imaps:
  - 172.30.0.126

openvpn_nft_client_rules:
  - name: localhost_dns
    clients:
      - lambda
      - alpha
  - name: localhost_ssh
    clients:
      - lambda
      - alpha
  - name: localhost_unifi
    clients:
      - lambda
      - zeta
  - name: localnet_ssh
    clients:
      - lambda
  - name: localnet_smb
    clients:
      - lambda
  - name: localnet_music
    clients:
      - lambda
  - name: localnet_imaps
    clients:
      - lambda

openvpn_nft_nbd_source_ipv4: 172.30.0.17
openvpn_nft_service_rules:
  - name: client_nbd
    clients:
      - gamma
